### ISSUE TITLE
希望能对高分屏支持优化一下

### ISSUE THREAD

**Issue by ciyeer** [Gaoyongxian666/CountBoard#5]
高分屏在圆角的地方锯齿非常严重，希望能优化一下，还有就是新建多个任务的时候，没有向下滚动的功能，滑动条也没有。。。。
革命尚未成功啊

**Comment by Gaoyongxian666** [comment]
这是因为windows对tkinter的画布没有提供抗锯齿，像osx提供反锯齿看起来会很丝滑。滚动条可以加上。
