### ISSUE TITLE
dpi模糊

### ISSUE THREAD

**Issue by carve-myself** [Gaoyongxian666/CountBoard#6]
电脑屏宽1920dpi不够,文字显示很模糊，2k屏则不会, 建议把ttkbootstrap升级到1.0   utility.enable_high_dpi_awareness()

1920屏幕
![image](https://user-images.githubusercontent.com/68720524/144062790-315e0fa5-a51d-4016-b0b5-7de7700c0ec3.png)

2k屏幕
![905536abe6e6b8930568124e946e59a](https://user-images.githubusercontent.com/68720524/144063341-5bd4bd53-5f14-4d09-9444-3d307597b72f.jpg)

ttkbootstrap升级到1.0后，1920屏幕
![image](https://user-images.githubusercontent.com/68720524/144062829-bf5673e1-a401-4112-8c97-d80300e13e7b.png)

**Comment by Gaoyongxian666** [comment]
好的，谢谢建议，我正在修改代码，一会儿更新一下。
