### ISSUE TITLE
网盘新版本  高清屏字体和窗口偏小

### ISSUE THREAD

**Issue by ooing** [Gaoyongxian666/CountBoard#7]
[![otXgo9.png](https://z3.ax1x.com/2021/12/02/otXgo9.png)](https://imgtu.com/i/otXgo9)

**Comment by ooing** [comment]
还有方便问下  本地如何构建 这个项目

**Comment by Gaoyongxian666** [comment]
你的显示器很大吗？是看不清吗？你屏幕的分辨率多少呢？

项目是开源的，你直接下载代码到本地，然后用Pyinstaller构建项目就可，我一会儿更新一下readme说一下如何打包。

**Comment by ooing** [comment]
我的电脑是小新pro13   屏幕的分辨率2.5K级别，16:10比例，像素2560×1600

**Comment by Gaoyongxian666** [comment]
问题看起来不大，主要我没高分辨的屏幕，等我下次更新的时候修改下。

**Comment by Gaoyongxian666** [comment]
或者你自己修改下大小，然后自己打包一下吧

**Comment by Gaoyongxian666** [comment]
我手边没有高分辨的屏幕，初步判断是我的代码写错了

utility.enable_high_dpi_awareness()

我把这句代码放到了tk里面，刚发现这是错误的。

你尝试将它放到tk外部看看怎么样

类似这样：

  if name == "main":
    utility.enable_high_dpi_awareness()
    main()

**Comment by ooing** [comment]
@Gaoyongxian666   为什么项目 没有  requirements.txt   原谅我糟糕的python

**Comment by Gaoyongxian666** [comment]
额，没有用到什么包

pip install apscheduler==3.6.3
pip install pywin32
pip install pywin10
pip install sqlitedict

**Comment by Gaoyongxian666** [comment]
分辨率bug已经修改了，查看1.3.0.2版本

**Comment by ooing** [comment]
@Gaoyongxian666   已经安装 正常显示了
