### ISSUE TITLE
新版本体验反馈

### ISSUE THREAD

**Issue by carve-myself** [Gaoyongxian666/CountBoard#8]
1.界面太迷你了 字体太小 需要凑近才能看清
![image](https://user-images.githubusercontent.com/68720524/144425193-4e7d746c-228e-4ebb-a93a-2a11cf58c3b0.png)

2.选择磁贴模式，窗口变形了
![image](https://user-images.githubusercontent.com/68720524/144425553-66f8e043-d861-4b10-84a5-7ea7023d8b27.png)

**Comment by Gaoyongxian666** [comment]
分辨率bug已经修改了，查看1.3.0.2版本
